"""
Provide the primary functions for preparing and processing FEP systems.
"""

from .utils import (
    run_with_log,
    antechamber,
    tleap,
    cpptraj,
    parmchk2,
    charmmlipid2amber,
    obabel,
    vmd)
import numpy as np
import os
import sys
import shutil
import subprocess as sp
import tempfile
import MDAnalysis as mda
from MDAnalysis.topology.guessers import guess_types
from MDAnalysis.analysis import align
import pandas as pd
from importlib import resources


from typing import List, Tuple
import loguru
from loguru import logger

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

# set info level for the logger
# logger.remove()
# logger.add(sys.stdout, level='INFO')


class System:
    """
    A class to represent and process a Free Energy Perturbation (FEP) system.

    It will be prepared in two stages: equil and fe. After the preparation
    of the equil system, run through the equilibration simulation and then
    prepare the fe system. The output of the equil system will be used as
    the input for the fe system.
    """

    def __init__(self,
                 stage: str,
                 system_name: str,
                 protein_input: str,
                 system_input: str,
                 system_dimensions: Tuple[float, float, float],
                 ligand_path: str,
                 receptor_segment: str = None,
                 protein_align: str = 'name CA and resid 60 to 250',
                 ligand_poses: List[str] = [],
                 output_dir: str = 'FEP',
                 retain_lig_h: bool = True,
                 ligand_ph: float = 7.4,
                 ligand_param: str = 'gaff2',
                 lipid_mol: List[str] = [],
                 lipid_ff: str = 'lipid21',
                 overwrite: bool = False,

                 ):
        """
        Initialize the FEPSystem class.

        Parameters
        ----------
        stage : str
            The stage of the FEP system. It can be 'equil' or 'fe'.
        system_name : str
            The name of the system.
        protein_input : str
            Path to the protein file in PDB format.
            It should be exported from Maestro,
            which means the protonation states of the protein are assigned
            (I think tleap can recongnize e.g ASP and ASH, maybe?).
            Water and ligand can be present in the file,
            but they will be removed during preparation.
        system_input : str
            A prepared simulation system with `dabble`.
            The ligand does not need to be present.
        system_dimensions : Tuple[float, float, float]
            The dimensions of the system in Angstroms.
            It can be read from INPCRD file generated by `dabble`
            along with the system_input PDB file.
        ligand_path : str
            Path to the ligand file.
        receptor_segment : str
            The segment of the receptor in the system_input.
            It will be used to set the protein anchor for the ligand.
            Default is None, which means all protein atoms will be used.
            Warning: if the protein for acnhoring
            is not the first protein entry of the system_input,
            it will cause problems when bat.py is trying to 
            get the protein anchor.
        protein_align : str
            The selection string for aligning the protein to the system.
            Default is 'name CA and resid 60 to 250'.
        ligand_poses : List[str], optional
            List of ligand poses to be included in the simulations.
            If it is empty, the pose from ligand_path will be used.
        output_dir : str
            Directory where output files will be saved.
        retain_lig_h : bool, optional
            Whether to retain hydrogens in the ligand. Default is True.
        ligand_ph : float, optional
            pH value for protonating the ligand. Default is 7.4.
        ligand_param : str, optional
            Parameter set for the ligand. Default is 'gaff'.
            Options are 'gaff' and 'gaff2'.
        lipid_mol : List[str], optional
            List of lipid molecules to be included in the simulations.
            Default is an empty list.
        lipid_ff : str, optional
            Force field for lipid atoms. Default is 'lipid21'.
        overwrite : bool, optional
            Whether to overwrite the existing files. Default is False.
        """
        self.stage = stage
        self.system_name = system_name
        self.protein_input = protein_input
        self.system_input = system_input
        self.system_dimensions = system_dimensions
        self.ligand_path = ligand_path
        self.receptor_segment = receptor_segment
        self.protein_align = protein_align
        self.ligand_poses = ligand_poses
        self.overwrite = overwrite

        # check input existence
        if not os.path.exists(protein_input):
            raise FileNotFoundError(f"Protein input file not found: {protein_input}")
        if not os.path.exists(system_input):
            raise FileNotFoundError(f"System input file not found: {system_input}")
        if not os.path.exists(ligand_path):
            raise FileNotFoundError(f"Ligand file not found: {ligand_path}")

        # set to absolute path
        self.output_dir = os.path.abspath(output_dir) + '/'
        if not os.path.exists(self.output_dir):
            if self.stage == 'equil':
                os.makedirs(self.output_dir)
            else:
                raise FileNotFoundError(
                    f"Output directory not found: {self.output_dir}"
                    "Please run the equilibration stage first")

        os.makedirs(f"{self.output_dir}/all-poses", exist_ok=True)
        os.makedirs(f"{self.output_dir}/build_files", exist_ok=True)

        os.makedirs(f"{self.stage_path}", exist_ok=True)
        os.makedirs(f"{self.stage_path}/ff", exist_ok=True)

        self.retain_lig_h = retain_lig_h
        self.ligand_ph = ligand_ph
        self.ligand_param = ligand_param
        if self.ligand_param not in ['gaff', 'gaff2']:
            raise ValueError(f"Invalid ligand_param: {self.ligand_param}"
                             "Options are 'gaff' and 'gaff2'")
        if self.ligand_param == 'gaff':
            raise NotImplementedError("gaff is not supported yet for dabble (maybe?)")
        self.lipid_mol = lipid_mol
        if not self.lipid_mol:
            self.membrane_simulation = False
        else:
            self.membrane_simulation = True
        self.lipid_ff = lipid_ff
        if self.lipid_ff != 'lipid21':
            raise ValueError(f"Invalid lipid_ff: {self.lipid_ff}"
                             "Only 'lipid21' is available")

        # Prepare the membrane parameters
        if self.membrane_simulation:
            self._prepare_membrane()

        self._get_alignment()
        if self.stage == 'equil':
            # Process the system
            overwite_system = self.overwrite
            if not os.path.exists(f"{self.output_dir}/all-poses/{self.system_name}_docked.pdb") or not os.path.exists(f"{self.output_dir}/build_files/reference.pdb"):
                overwite_system = True
            if overwite_system:
                self._process_system()
            # Process ligand and prepare the parameters
            overwite_ligand = self.overwrite
            if not os.path.exists(f"{self.output_dir}/ff/ligand.lib"):
                overwite_ligand = True
            if overwite_ligand:
                self._process_ligand()

            self._prepare_ligand_poses()

            # Prepare the system
            self._prepare_system()

    def _get_alignment(self):
        """
        Prepare for the alignment of the protein and ligand to the system.
        """
        u_prot = mda.Universe(self.protein_input)
        u_sys = mda.Universe(self.system_input, format='XPDB')

        # get translation-rotation matrix
        mobile = u_prot.select_atoms(self.protein_align).select_atoms('name CA')
        ref = u_sys.select_atoms(self.protein_align).select_atoms('name CA')

        mobile_com = mobile.center(weights=None)
        ref_com = ref.center(weights=None)
        mobile_coord = mobile.positions - mobile_com
        ref_coord = ref.positions - ref_com

        _ = align._fit_to(
            mobile_coordinates=mobile_coord,
            ref_coordinates=ref_coord,
            mobile_atoms=u_prot.atoms,
            mobile_com=mobile_com,
            ref_com=ref_com)

        self.u_prot = u_prot
        self.u_sys = u_sys
        # store these for ligand alignment
        self.mobile_com = mobile_com
        self.ref_com = ref_com
        self.mobile_coord = mobile_coord
        self.ref_coord = ref_coord

    def _process_system(self):
        """
        Generate the protein, reference, and lipid (if applicable) files.
        We will align the protein_input to the system_input because
        the system_input is generated by dabble and may be shifted;
        we want to align the protein to the system so the membrane is 
        properly positioned.
        """
        u_prot = self.u_prot
        u_sys = self.u_sys

        membrane_ag = u_sys.select_atoms(f'resname {" ".join(self.lipid_mol)}')
        logger.debug(f'Number of lipid molecules: {membrane_ag.n_residues}')
        water_ag = u_sys.select_atoms('byres (resname TIP3 and around 20 (protein or resname POPC))')
        logger.debug(f'Number of water molecules: {water_ag.n_residues}')

        # modify the chaininfo to be unique for each segment
        current_chain = 66
        u_prot.atoms.tempfactors = 0
        for segment in u_sys.select_atoms('protein').segments:
            resid_seg = segment.residues.resids
            resid_seq = " ".join([str(resid) for resid in resid_seg])
            chain_id = segment.atoms.chainIDs[0]
            u_prot.select_atoms(
                f'resid {resid_seq} and chainID {chain_id} and protein').atoms.tempfactors = current_chain
            current_chain += 1
        u_prot.atoms.chainIDs = [chr(int(chain_nm)) for chain_nm in u_prot.atoms.tempfactors]

        if self.receptor_segment:
            protein_anchor = u_prot.select_atoms(f'segid {self.receptor_segment} and protein')
            protein_anchor.atoms.chainIDs = 'A'
            protein_anchor.atoms.tempfactors = 65
            other_protein = u_prot.select_atoms(f'not segid {self.receptor_segment} and protein')
            u_merged = mda.Merge(protein_anchor,
                                 other_protein,
                                 membrane_ag,
                                 water_ag)
        else:
            u_merged = mda.Merge(u_prot.select_atoms('protein'),
                                 membrane_ag,
                                 water_ag)
        water = u_merged.select_atoms('resname TIP3')
        logger.debug(f'Number of water molecules in merged system: {water.n_residues}')
        logger.debug(f'Water atom names: {water.residues[0].atoms.names}')

        # Otherwise tleap cannot recognize the water molecules
        water.select_atoms('name OW').names = 'O'
        water.select_atoms('name OH2').names = 'O'

        box_dim = np.zeros(6)
        if len(self.system_dimensions) == 3:
            box_dim[:3] = self.system_dimensions
            box_dim[3:] = 90.0
        elif len(self.system_dimensions) == 6:
            box_dim = self.system_dimensions
        else:
            raise ValueError(f"Invalid system_dimensions: {self.system_dimensions}")
        u_merged.dimensions = box_dim
        # save as *_docked.pdb that matched `input-dd-amber.in`
        u_merged.atoms.write(f"{self.output_dir}/all-poses/{self.system_name}_docked.pdb")
        protein_ref = u_prot.select_atoms('protein')
        protein_ref.write(f"{self.output_dir}/all-poses/reference.pdb")

    def _process_ligand(self):
        """
        Process the ligand, including adding or removing hydrogens as needed.
        """

        # Ensure the ligand file is in PDB format
        logger.info(f'Processing ligand file: {self.ligand_path}')

        ligand = mda.Universe(self.ligand_path)
        converted_path = f"{self.output_dir}/ligand.pdb"
        ligand.atoms.write(converted_path)
        self.ligand_path = converted_path

        # retain hydrogens from the ligand
        if self.retain_lig_h:
            # convert mol2 to get charge
            try:
                shutil.copy(self.ligand_path, f"{self.output_dir}/ligand.pdb")
            except shutil.SameFileError:
                pass
            run_with_log(f"{obabel} -i pdb {self.ligand_path} -o mol2 -O {self.output_dir}/ligand.mol2")

        else:
            # Remove hydrogens from the ligand
            noh_path = f"{self.output_dir}/ligand_noh.pdb"
            run_with_log(f"{obabel} -i pdb {self.ligand_path} -o pdb -O {noh_path} -d")

            # Add hydrogens based on the specified pH
            run_with_log(f"{obabel} -i pdb {noh_path} -o pdb -O {self.output_dir}/ligand.pdb -p {self.ligand_ph:.2f}")
            run_with_log(f"{obabel} -i pdb {noh_path} -o mol2 -O {self.output_dir}/ligand.mol2 -p {self.ligand_ph:.2f}")

        self.ligand_path = f"{self.output_dir}/ligand.pdb"
        self.ligand = mda.Universe(self.ligand_path)
        self.ligand_mol2_path = f"{self.output_dir}/ligand.mol2"
        ligand_mol2 = mda.Universe(self.ligand_mol2_path)

        self.ligand_charge = np.round(np.sum(ligand_mol2.atoms.charges))
        logger.info(f'The babel protonation of the ligand is for pH {self.ligand_ph:.2f}')
        logger.info(f'The net charge of the ligand is {self.ligand_charge}')

        # For now, we don't need to prepare ligand parameters
#        self._prepare_ligand_parameters()

    def _prepare_ligand_parameters(self):
        """Prepare ligand parameters for the system"""
        # Get ligand parameters
        logger.info('Preparing ligand parameters')
        # antechamber_command = f'{antechamber} -i {self.ligand_path} -fi pdb -o {self.output_dir}/ligand_ante.mol2 -fo mol2 -c bcc -s 2 -at {self.ligand_param} -nc {self.ligand_charge}'
        antechamber_command = f'{antechamber} -i {self.ligand_mol2_path} -fi mol2 -o {self.output_dir}/ligand_ante.mol2 -fo mol2 -c bcc -s 2 -at {self.ligand_param} -nc {self.ligand_charge}'
        with tempfile.TemporaryDirectory() as tmpdir:
            run_with_log(antechamber_command, working_dir=tmpdir)
        shutil.copy(f"{self.output_dir}/ligand_ante.mol2", f"{self.stage_path}/ff/ligand.mol2")
        self.ligand_mol2_path = f"{self.stage_path}/ff/ligand.mol2"

        if self.ligand_param == 'gaff':
            run_with_log(f'{parmchk2} -i {self.output_dir}/ligand_ante.mol2 -f mol2 -o {self.output_dir}/ligand.frcmod -s 1')
        elif self.ligand_param == 'gaff2':
            run_with_log(f'{parmchk2} -i {self.output_dir}/ligand_ante.mol2 -f mol2 -o {self.output_dir}/ligand.frcmod -s 2')
        shutil.copy(f"{self.output_dir}/ligand.frcmod", f"{self.stage_path}/ff/ligand.frcmod")

        with tempfile.TemporaryDirectory() as tmpdir:
            #    run_with_log(f'{antechamber} -i {self.ligand_path} -fi pdb -o {self.output_dir}/ligand_ante.pdb -fo pdb', working_dir=tmpdir)
            run_with_log(
                f'{antechamber} -i {self.ligand_mol2_path} -fi mol2 -o {self.output_dir}/ligand_ante.pdb -fo pdb', working_dir=tmpdir)

        # get lib file
        tleap_script = f"""
        source leaprc.protein.ff14SB
        source leaprc.{self.ligand_param}
        lig = loadmol2 {self.stage_path}/ff/ligand.mol2
        loadamberparams {self.stage_path}/ff/ligand.frcmod
        saveoff lig {self.stage_path}/ff/ligand.lib
        saveamberparm lig {self.stage_path}/ff/ligand.prmtop {self.stage_path}/ff/ligand.inpcrd

        quit
        """
        with open(f"{self.output_dir}/tleap.in", 'w') as f:
            f.write(tleap_script)
        run_with_log(f"{tleap} -f {self.output_dir}/tleap.in")

        logger.info('Ligand parameters prepared')

    def _prepare_ligand_poses(self):
        """
        Prepare ligand poses for the system.
        """
        if not self.ligand_poses:
            self.ligand_poses = [self.ligand_path]

        new_pose_paths = []
        for i, pose in enumerate(self.ligand_poses):
            # align to the system
            u = mda.Universe(pose)
            self._align_2_system(u.atoms)
            u.atoms.write(f"{self.output_dir}/all-poses/pose{i}.pdb")
            pose = f"{self.output_dir}/all-poses/pose{i}.pdb"

            if not self.retain_lig_h:
                noh_path = f"{self.output_dir}/all-poses/pose{i}_noh.pdb"
                run_with_log(f"{obabel} -i pdb {pose} -o pdb -O {noh_path} -d")

                # Add hydrogens based on the specified pH
                run_with_log(f"{obabel} -i pdb {noh_path} -o pdb -O {pose} -p {self.ligand_ph:.2f}")

            if not os.path.exists(f"{self.output_dir}/all-poses/pose{i}.pdb"):
                shutil.copy(pose, f"{self.output_dir}/all-poses/pose{i}.pdb")

            new_pose_paths.append(f"{self.output_dir}/all-poses/pose{i}.pdb")

        self.ligand_poses = new_pose_paths

    def _align_2_system(self, mobile_atoms):
        _ = align._fit_to(
            mobile_coordinates=self.mobile_coord,
            ref_coordinates=self.ref_coord,
            mobile_atoms=mobile_atoms,
            mobile_com=self.mobile_com,
            ref_com=self.ref_com)

    def _prepare_membrane(self):
        """
        Prepare the membrane by converting CHARMM or 
        conventional lipid names into lipid21 names
        which e.g. for POPC, it will be PC, PA, OL.
        see: https://ambermd.org/AmberModels_lipids.php
        """
        logger.info('Preparing the membrane system')

        # read charmmlipid2amber file
        charmm_csv_path = resources.files("batter") / "data/charmmlipid2amber.csv"
        charmm_amber_lipid_df = pd.read_csv(charmm_csv_path, header=1, sep=',')

        lipid_mol = self.lipid_mol
        logger.info(f'Converting lipid input: {lipid_mol}')
        amber_lipid_mol = charmm_amber_lipid_df.query('residue in @lipid_mol')['replace']
        amber_lipid_mol = amber_lipid_mol.apply(lambda x: x.split()[1]).unique().tolist()

        # extend instead of replacing so that we can have both
        lipid_mol.extend(amber_lipid_mol)
        self.lipid_mol = lipid_mol
        logger.info(f'New lipid_mol list: {self.lipid_mol}')

    def _prepare_system(self):
        """
        Prepare the system for the FEP simulation.
        """
        logger.info('Preparing the system')

        logger.info('System prepared')

    @property
    def stage_path(self):
        """Return the path to the stage directory."""
        return f'{self.output_dir}/{self.stage}'
