name: batter
channels:
  - conda-forge
  - defaults
dependencies:
  # Conda dependencies
  - python >=3.11
  - pip
  - ambertools >=23.6
  - openbabel
  - pandas >=2.2,<3
  - pillow >=9,<12.3
  - prettypyplot
  - seaborn
  - loguru
  - pydantic >=2.11.7
  - click  >=8.2.0
  - MDAnalysis >=2.9.0
  - jax
  - pymbar >4.0
  - scipy >=1.11,<1.17
  # dask distributed for analysis
  - dask
  - dask-jobqueue
  - distributed
  # openfe
  - gufe >=1.7.0
  - openff-interchange
  - openff-interchange-base >=0.5.0,!=0.5.1
  - openff-toolkit-base >=0.16.2
  - kartograf
  - konnektor
  - cinnabar
  # Tests
  - pytest
  - pytest-xdist
  - pytest-cov
  - pytest-snapshot
  
  - pip:
    - -e ./extern/ParmEd
    - -e ./extern/alchemlyb
    - -e ./extern/rocklinc
    - nglview  
