#!/bin/bash

#SBATCH --job-name="SYSTEMNAME-STAGE-POSE"
#SBATCH --partition=rondror
#SBATCH --nodes=1
#SBATCH --output=STAGE-POSE-%j.out
#SBATCH --error=STAGE-POSE-%j.err
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH -t 12:00:00

# Main command goes here
scontrol show job $SLURM_JOB_ID

source $GROUP_HOME/software/amber24/setup_amber.sh > /dev/null 2>&1

# Define the maximum number of attempts
MAX_ATTEMPTS=3
RETRY_COUNT=${RETRY_COUNT:-1}  # Default to 1 if not set

# Run the simulation
echo "Attempt $RETRY_COUNT to run simulations..."
source run-local.bash 2>&1 | tee run.log
error_code=${PIPESTATUS[0]}  # Capture the exit status of 'source run-local.bash'

if [ $error_code -eq 0 ]; then
    echo "Simulation completed successfully on attempt $RETRY_COUNT."
else
    echo "Simulation failed with error code $error_code on attempt $RETRY_COUNT."

    # Check if the maximum attempts have been reached
    if [ $RETRY_COUNT -lt $MAX_ATTEMPTS ]; then
        NEXT_RETRY=$((RETRY_COUNT + 1))
        echo "Resubmitting the job for attempt $NEXT_RETRY..."
        # Submit the same script with an incremented retry count
        sbatch --export=RETRY_COUNT=$NEXT_RETRY $0
        exit 0
    else
        echo "FAILED" > FAILED
        echo "Maximum attempts ($MAX_ATTEMPTS) reached. Simulation failed."
        exit 1
    fi
fi

# write FINISHED to a file
echo "FINISHED" > FINISHED
exit 0