version: 1
protocol: rbfe_septop
backend: local

create:
  system_name: CHK1_3u9n_corehop
  protein_input: /home/users/yuzhuang/yuzhuang_scratch/public_binding_free_energy_benchmark_new/fep_benchmark_inputs/structure_inputs/batter_run/CHK1_scaffold_hopping/INPUTS/CHK1_3u9n_corehop_protein.pdb
  ligand_input: /home/users/yuzhuang/yuzhuang_scratch/public_binding_free_energy_benchmark_new/fep_benchmark_inputs/structure_inputs/batter_run/CHK1_scaffold_hopping/ligand_dict.json
  ligand_ff: openff-2.3.0
  retain_lig_prot: true
  param_charge: "openff-gnn-am1bcc-1.0.0.pt"
  overwrite: false
  receptor_ff: protein.ff19SB
  solv_shell: 15.0
  water_model: OPC

run:
  output_folder: ../network_runs/chk1_redundant_oneway
  run_id: rep1
  only_rbfe_network: true
  max_workers: 8
  on_failure: raise

fe_sim: {}

rbfe:
  mapping: konnektor
  konnektor_layout: redundantminimalspanningtree
  both_directions: false
  atom_mapper: kartograf
  kartograf:
    atom_max_distance: 0.95
    map_exact_ring_matches_only: true
    allow_partial_fused_rings: true
    allow_bond_breaks: false

