"""
This script is used to run the pipeline.

The pipeline is used to calculate the absolute binding free energy of a ligand to a protein
in a lipid bilayer.

Arguments:
    input (str): Path to the system JSON file (generated by prepare_template.ipynb).
    param (str): Path to the input file for the ABFE calculation.
    output_folder (str): Path to the output folder for the simulation.
    overwrite (bool): If set, existing output will be overwritten.
    only_equil (bool): If set, only the equilibration step will be run (default: False).
"""

import click
import os
import json
import sys
from batter import MABFESystem, RBFESystem


@click.command()
@click.option('--input', required=True, type=click.Path(exists=True), help='Path to the system JSON file.')
@click.option('--param', required=True, type=click.Path(exists=True), help='Path to the ABFE input configuration file.')
@click.option('--output-folder', required=True, type=str, help='Output folder for the simulation.')
@click.option('--overwrite', is_flag=True, default=False, help='If set, overwrite existing output folders.')
@click.option('--only-equil', is_flag=True, default=False, help='If set, only run the equilibration step.')
def run_pipeline(input, param, output_folder, overwrite, only_equil):
    """Run the ABFE pipeline."""
    click.echo(f"Running ABFE pipeline...")
    click.echo(f"System JSON: {input}")
    click.echo(f"Input param file: {param}")
    click.echo(f"Output folder: {output_folder}")
    click.echo(f"Overwrite: {overwrite}")
    click.echo(f"Only equilibration: {only_equil}")

    # Load the system JSON file
    with open(input, 'r') as f:
        system_data = json.load(f)
    protein_name = system_data['protein']
    protein_file = system_data['protein_input']
    system_file = system_data['system_input']
    equilibrated_rst = system_data['system_rst7_input']
    anchor_atoms = system_data['anchor_atoms']
    extra_restraints = system_data.get('extra_restraints', None)

    ligand_json = system_data['ligand_input']
    with open(ligand_json, 'r') as f:
        ligand_files = json.load(f)
    
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    click.echo(f"Protein file: {protein_file}")
    click.echo(f"System file: {system_file}")
    click.echo(f"Equilibrated RST file: {equilibrated_rst}")
    click.echo(f"Ligand files: {ligand_files}")
    click.echo(f"Anchor atoms: {anchor_atoms}")
    click.echo(f"Extra restraints: {extra_restraints}")

    system = MABFESystem(folder=output_folder)

    system.create_system(
                system_name=protein_name,
                protein_input=protein_file,
                system_topology=system_file,
                system_coordinate=equilibrated_rst,
                ligand_paths=ligand_files,
                overwrite=overwrite,
                retain_lig_prot=True,
                lipid_mol=['POPC'],
                anchor_atoms=anchor_atoms,
    )

    system.run_pipeline(
        input_file=param,
        only_fe_preparation=only_equil,
        extra_restraints=extra_restraints,
    )

if __name__ == '__main__':
    run_pipeline()