#!/bin/bash

#SBATCH --job-name="COMPONENT-remd"
#SBATCH --partition=PARTITIONNAME
#SBATCH --open-mode=append
#SBATCH --output=COMPONENT-remd-%j.out
#SBATCH --error=COMPONENT-remd-%j.err
#SBATCH --cpus-per-task=1
#SBATCH -t 16:00:00
#SBATCH -d singleton
#SBATCH --nodes=1
#SBATCH --gpus=NWINDOWS

scontrol show job ${SLURM_JOB_ID}
echo "Job started at $(date)"

export COMP="COMPONENT"
export NWINDOWS="NWINDOWS"
export FERANGE="FERANGE"
export PFOLDER="."
export OVERWRITE=${OVERWRITE:-0}

source AMBER_SETUP_SH > /dev/null 2>&1

./run-local-remd.bash
exit $?
