name: docs_batter
channels:
  - conda-forge
  - defaults
dependencies:
  # Base
  - python>=3.11
  - pip

  # Sphinx + theme/extensions used in conf.py
  - sphinx>=7.2
  - pydata-sphinx-theme>=0.15
  - sphinx-design>=0.6
  - sphinx-copybutton>=0.5

  # Pydantic autodoc (you enabled sphinxcontrib.autodoc_pydantic)
  - pip:
      - autodoc_pydantic
      - pydantic>=2.0
      - -e ../
